config/routes.rb
Rails.application.routes.draw do


 
 	

 	root 'static_pages#home'
 	
  get '/about',				to: 'static_pages#about'
  get '/signup', 			to: 'users#new'
  post '/signup', 		to: 'users#create'
  get '/login', 			to: 'sessions#new'
  post '/login', 			to: 'sessions#create'
  delete '/logout', 	to: 'sessions#destroy'
  get '/attend/:id',  to: 'event_attendees#new'
  post '/attend/',  to: 'event_attendees#create'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		@events = Event.all 
			@upcoming_events = Event.upcoming.order(:date).paginate(page: params[:page], per_page: 10)
  	end	
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<head>
		<title>Private Events <%= yield(:title) %> </title>
	</head>
	<body>
		<div class="container">
			<div class="row home_page">
				<div class="col-sm-7">
					<h1>Private Events</h1>
				</div>
				<div class="col-sm-5">
					<%= link_to "Create new event", new_event_path, class: "btn btn-lg btn-primary" %>
				</div>	
			</div>
			<div class="row">
				<div class="col events-wrapper">
					<% if @events.any? %>
					<%= render 'events/upcoming_events' %>
					<% end %>
				</div>
			</div>

		</div>
		
	</body>
</html>

app/views/static_pages/_logged_out.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<head>
		<title>Private Events <%= yield(:title) %> </title>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-sm h-50 welcome">
					<h1>Welcome</h1>
					<p>This is Private Events. A site to create and promote your events.<br> Please log in or sign up if you are not already a member.</p>
					<div class="text-center">
						<%= link_to "Login", login_path, class: "btn btn-lg btn-primary" %>
						<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm">
					<p>This is a project created for the Odin Project. To see all the features you can create your own account or if you would just like to look around you can use this guest account.  </p>
					<p>Email: guest@example.com</p>
					<p>Password: privateevents</p>
				</div>
				</div>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron jumbotron-fluid">
<div class="container about">
	<div class="row">
		<div class="col">
			App created by Jamesredux as part of the Odin Project
			Ruby on Rails section - <a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations">Associations project.</a>
			
		</div>
		<div class="col">
			<ul>
			<li><%= link_to "Jamesredux's Github", 'https://github.com/Jamesredux' %></li>
			<li><%= link_to "The Odin Project", 'https://www.theodinproject.com/home' %></li>
			
		</ul>
		</div>	
	</div>

	<div class="row">
		<div class="col">
			
		</div>
		
		<div class="col">
			
		</div>	
	</div>

</div>

</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<%= render 'static_pages/logged_in' %>
<% else %>
	<%= render 'static_pages/logged_out' %>
<% end %>