config/routes.rb
Rails.application.routes.draw do


 
 	

 	root 'static_pages#home'
 	
  get '/about',				to: 'static_pages#about'
  get '/signup', 			to: 'users#new'
  post '/signup', 		to: 'users#create'
  get '/login', 			to: 'sessions#new'
  post '/login', 			to: 'sessions#create'
  delete '/logout', 	to: 'sessions#destroy'
  get '/attend/:id',  to: 'event_attendees#new'
  post '/attend/',  to: 'event_attendees#create'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events 
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-nav navbar-expand-lg navbar-dark bg-dark">
  		<div class="container">
  			<%= link_to "Private Events", root_path, id: "logo" %>
  			<nav>
  				<ul class="nav navbar-nav navbar-right ">
  					<li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
  					<li><%= link_to "Events", events_path %></li>

            <% if logged_in? %>
              <li><%= link_to current_user.name, current_user %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                    <% if current_user.admin? %>
                      <li><%= link_to "Users", users_path %>
                    <% end %>                         
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                  
                </ul>
              </li>
            <% else %>  
  					 <li><%= link_to "Log in", login_path %></li>
            <% end %> 
  				</ul> 					
  			</nav>
  		</div>
</header>      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">		
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>  
    	<%= yield %>
     
  	</div>  
  </body>
</html>